/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch/$videoId'
import { Route as ApiDiscoverRouteImport } from './routes/api/discover'
import { Route as ApiWatchVideoIdRouteImport } from './routes/api/watch/$videoId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverRoute = ApiDiscoverRouteImport.update({
  id: '/api/discover',
  path: '/api/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchVideoIdRoute = ApiWatchVideoIdRouteImport.update({
  id: '/api/watch/$videoId',
  path: '/api/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/discover': typeof ApiDiscoverRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/watch/$videoId': typeof ApiWatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/discover': typeof ApiDiscoverRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/watch/$videoId': typeof ApiWatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/discover': typeof ApiDiscoverRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/watch/$videoId': typeof ApiWatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/discover'
    | '/watch/$videoId'
    | '/api/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/discover'
    | '/watch/$videoId'
    | '/api/watch/$videoId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/discover'
    | '/watch/$videoId'
    | '/api/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDiscoverRoute: typeof ApiDiscoverRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  ApiWatchVideoIdRoute: typeof ApiWatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover': {
      id: '/api/discover'
      path: '/api/discover'
      fullPath: '/api/discover'
      preLoaderRoute: typeof ApiDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/$videoId': {
      id: '/api/watch/$videoId'
      path: '/api/watch/$videoId'
      fullPath: '/api/watch/$videoId'
      preLoaderRoute: typeof ApiWatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDiscoverRoute: ApiDiscoverRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  ApiWatchVideoIdRoute: ApiWatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
